---
title: "SUPPLEMENT"
subtitle: "The effectiveness of COVID-19 vaccines to prevent post COVID cardiac and thromboembolic complications"
format:
  docx:
    reference-doc: reference-doc.docx
    fig-cap-location: top
execute:
  echo: false
toc: TRUE
---

```{r, warning=FALSE, results='hide', cache.comments=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(flextable)
library(survival)
library(ggplot2)
library(ggfortify)
library(survminer)
library(ggh4x)
library(officer)
library(knitr)
library(officedown)
library(grid)

knitr::opts_chunk$set(
  echo       = FALSE,
  message    = FALSE,
  warning    = FALSE
)
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE, tab.cap.pre = "Table ", tab.cap.sep = ": ")
num_tab <- 1
num_fig <- 1
```

```{r, warning=FALSE, results='hide', cache.comments=FALSE, message=FALSE}
source(here("functions_pacs.R"))
```

```{r, warning=FALSE, results='hide', cache.comments=FALSE, message=FALSE}
source(here("prep_data_uio.R"))
```


```{r, warning=FALSE, cache.comments=FALSE, message=FALSE, results='asis'}
# Table Outcome VE ----
for (ii in 2:nrow(captions_outcome)) {
  table <- getDataForOutcomeTable(captions_outcome, ii, estimates, order_sup)
  
  cohort_ind <-  which(!is.na(table$`Staggered cohort`))
  by_window <- length(unique(table$`Post COVID outcomes`))-1
  
  borders_i <- seq(by_window + 1, cohort_ind[2], by_window)
  for (jj in 2:(length(cohort_ind))) {
    if (jj > length(cohort_ind)) {
      borders_i <- c(borders_i, seq(cohort_ind[jj]+by_window, cohort_ind[jj+1], by_window))
    }
  }
   borders_i <- c(borders_i, seq(cohort_ind[length(cohort_ind)]+by_window, nrow(table), by_window))
  
   cat("\n") 
    cat("##", paste0("**Table S", num_tab, ": ", captions_outcome$caption_1[ii], "**", captions_outcome$caption_2[ii]))
  flextable_to_rmd(
    table %>%
      rename("Cohort" = "Staggered cohort",
             "Outcome" = "Post COVID outcomes",
             "Time window" = "Days since COVID-19") %>%
      flextable() %>%
      separate_header(opts = "center-hspan") %>%
      hline(border = border, j = 3:ncol(table)) %>%
      hline(border = border, j = 2:ncol(table), 
            i = borders_i) %>%
      hline(border = border, j = 1:ncol(table), i =  cohort_ind) %>%
      hline(border = border, j = 1:ncol(table), i = (cohort_ind[2:length(cohort_ind)]-1)) %>%
      bold(part = "header") %>%
      bold(j = 1:3, part = "body") %>%
      bold(i =  cohort_ind, part = "body") %>%
      bg(j = seq(2, ncol(table), 2), bg = "#ededed") %>%
      align(align = "center", part = "header") %>%
      align(align = "left", part = "body") %>%
      set_table_properties(layout = "autofit") %>%
      merge_at(i = 1:2, j = 1, part = "header") %>%
      merge_at(i = 1:2, j = 2, part = "header") %>%
      merge_at(i = 1:2, j = 3, part = "header") %>%
      fontsize(size = 7, part = "header") %>%
      fontsize(size = 7, part = "body") %>%
      padding(padding = 1, part = "all")
  )
  cat("VTE = Venous thromboembolism (DVT + PE), DVT = Deep vein thrombosis, PE = Pulmonary embolism,
      ATE = Arterial thrombosis/thromboembolism (IS + TIA + MI), IS = Ischemic stroke, TIA = Transient ischemic attack,
      MI = Myocardial infarction, HF = Heart failure, HS = Hemorrhagic stroke, MP = Myocarditis or Pericarditis")
  cat("\n\n\\pagebreak\n")
    num_tab <- num_tab + 1
}


```

